# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test
  - dockerize
  - deploy

variables:
  PROJECT_NAME: sawatech
  BACKEND_PATH: aspnet-core
  FRONTEND_PATH: angular
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $FRONTEND_PATH/node_modules/
    - $YARN_CACHE_FOLDER/

# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings

# Build .NET Backend
build_backend:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - cd $BACKEND_PATH/src/SawaTech.PropertyMini.HttpApi.Host
    - dotnet restore
    - dotnet build --configuration Release
  artifacts:
    paths:
      - $BACKEND_PATH/src/SawaTech.PropertyMini.HttpApi.Host/bin/

# Build Angular Frontend
build_frontend:
  stage: build
  image: node:20
  before_script:
    - yarn set version stable
  script:
    - yarn install --frozen---frozen-lockfile
    - yarn build ----configuration production
  artifacts:
    paths:
      - $FRONTEND_PATH/dist/

# Run Tests
test_backend:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - cd $BACKEND_PATH/test
    - dotnet test

# Dockerize app
dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $PROJECT_NAME-backend $BACKEND_PATH/src/SawaTech.PropertyMini.HttpApi.Host
    - docker build -t $PROJECT_NAME-frontend $FRONTEND_PATH
    - docker-compose up -d

# Local Deploy (dev machine with SSH access)
deploy_local:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh
  script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
    - scp -i id_rsa docker-compose.yml user@local-dev-machine:/path/to/deploy
    - ssh -i id_rsa user@local-dev-machine "cd /path/to/deploy && docker-compose pull && docker-compose up -d"

# Deploy to production
deploy_prod:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh-client docker-cli
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - echo "$DOCKER_CONFIG" > ~/.docker/config.json
  script:
    - ssh -o StrictHostKeyChecking=no user@server "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -o StrictHostKeyChecking=no user@server "docker pull $CI_REGISTRY_IMAGE/backend:latest"
    - ssh -o StrictHostKeyChecking=no user@server "docker pull $CI_REGISTRY_IMAGE/frontend:latest"
    - ssh -o StrictHostKeyChecking=no user@server "docker-compose -f /path/to/docker-compose.yml up -d"