# services:
#   angular:
#     image: sawatech-angular
#     build: ./angular
#     ports:
#       - "4200:80"
#     depends_on:
#       - backend_api

#   backend_api:
#     image: sawatech-backend-api
#     build: 
#       context: .
#       dockerfile: aspnet-core/src/SawaTech.PropertyMini.HttpApi.Host/Dockerfile
#     ports:
#       - "5000:80"
#     env_file:
#       - .env.ci
#     depends_on:
#       - db

#   migration_runner:
#     image: sawatech-migration
#     build:
#       context: .
#       dockerfile: aspnet-core/src/SawaTech.PropertyMini.HttpApi.Host/Dockerfile.migrations
#     depends_on:
#       - db
#     working_dir: /src
#     env_file:
#       - .env.ci
#     command: dotnet-ef database update --project ./aspnet-core/src/SawaTech.PropertyMini.EntityFrameworkCore --startup-project ./aspnet-core/src/SawaTech.PropertyMini.HttpApi.Host
    
#   db:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     ports:
#       - "1433:1433"
#     environment:
#       ACCEPT_EULA: "Y"
#       SA_PASSWORD: "YourStrong@Passw0rd_CI"
#     volumes:
#       - mssql_data:/var/opt/mssql/data
#       - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   mssql_data:
#     driver: local
version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - backend

  angular:
    image: sawatech-angular
    build: 
      context: ./angular
      args:
        - SONAR_TOKEN=${SONAR_TOKEN}
    ports:
      - "4200:80"
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
    depends_on:
      - backend_api
      - sonarqube
    networks:
      - backend

  backend_api:
    image: sawatech-backend-api
    build: 
      context: .
      dockerfile: aspnet-core/src/SawaTech.PropertyMini.HttpApi.Host/Dockerfile
      args:
        - SONAR_TOKEN=${SONAR_TOKEN}
    ports:
      - "5000:80"
    env_file:
      - .env.ci
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
    depends_on:
      - db
      - sonarqube
    networks:
      - backend

  migration_runner:
    image: sawatech-migration
    build:
      context: .
      dockerfile: aspnet-core/src/SawaTech.PropertyMini.HttpApi.Host/Dockerfile.migrations
    depends_on:
      - db
    working_dir: /src
    env_file:
      - .env.ci
    command: dotnet-ef database update --project ./aspnet-core/src/SawaTech.PropertyMini.EntityFrameworkCore --startup-project ./aspnet-core/src/SawaTech.PropertyMini.HttpApi.Host
    networks:
      - backend
    
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
    volumes:
      - mssql_data:/var/opt/mssql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

volumes:
  mssql_data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local

networks:
  backend:
    driver: bridge