# version: '3.8'

# services:
#   angular:
#     image: sawatech-angular
#     build: ./angular
#     ports:
#       - "4200:80"
#     depends_on:
#       - backend_api

#   backend_api:
#     image: sawatech-backend-api
#     build: ./aspnet-core/src/SawaTech.PropertyMini.HttpApi.Host
#     ports:
#       - "5000:80"
#     env_file:
#       - .env.ci
#     depends_on:
#       - db
    
#   db:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     ports:
#       - "1433:1433"
#     environment:
#       ACCEPT_EULA: "Y"
#       SA_PASSWORD: "YourStrong@Passw0rd"
#     volumes:
#       - mssql_data:/var/opt/mssql/data
version: "3.9"
services:
  backend:
    image: sawatech-backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    image: sawatech-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
